apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-ca
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/part-of: hyrox-platform
data:
  # Certificado de la CA que firma el del broker. Es público: los clientes lo
  # usan para validar el servidor en el handshake TLS, no contiene secreto.
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDETCCAfmgAwIBAgIUVdGuVEh1cQBvdTiLFH/+avlaCwowDQYJKoZIhvcNAQEL
    BQAwGDEWMBQGA1UEAwwNaHlyb3gtbXF0dC1jYTAeFw0yNjA3MjIxMTEyMTlaFw0z
    NjA3MTkxMTEyMTlaMBgxFjAUBgNVBAMMDWh5cm94LW1xdHQtY2EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDLe7asWd1aYaG7iJ/eMjrPvsSMwPTpGYcf
    Xbpn2/r22RTVgc8Sx0rbZxwh9sskOCf3f6tgr5l04aE1w3yobn/hYl0YRdZ7xovi
    xpZB0FVbk0ap7LdfwzZdkFWD4F4gEtt1nhszxWfgHI8HMZSwoBn5IAioePQ/8ErF
    5ivDcn+cCYR2w6GZYp2mQh18eyQAiYC79DVEC3i9oSJiEN1puxQph5Scpke7K/4E
    fBuOXQfojB2UrzydSVmcURf74IOb06LxsG4eeh0wpJtW8D8KaAQEm3iIKz9wk8vX
    TIQn/kwApwo9TzlEx1cJLVcjAXxmoYnxq9TPZcFLfNUzfWOGKOFhAgMBAAGjUzBR
    MB0GA1UdDgQWBBRf8aNHpfQLD5z2lCtTgZ/5VW+2cjAfBgNVHSMEGDAWgBRf8aNH
    pfQLD5z2lCtTgZ/5VW+2cjAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUA
    A4IBAQC8tsBvlTcR28+F2LEp6OC6KJvra2SEmrhI4r/EOpUT9pWuQNgd/V7YTq2V
    Fe3ss0jzIlQVbT7nmX9gfL2VfEn9Sd15wkIgIw72TME+d+DASvOsYYgSlbsvNeAZ
    pSdq02Nt0bYlHakXn7FQ0VWQ89M26qKix1U0VsuRDn/SQym/ETOEa6zV/PwrWeFY
    unuftWUKGeHyFgrIJ0U9XNaEVTvpLRpYXwEqjSqcB+wWFsH3ax8sgOs+vt2y0HYm
    kofedyDFpVi5M7ov54nw/K3LgDAq89vQzvKTyM2wu8NBFeC1J5Z1TS0WqreODuv7
    IJ7/LmjHVw2cBuWl2kWfD+T0HMz+
    -----END CERTIFICATE-----
