---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: device-broker
  namespace: hyrox
spec:
  encryptedData:
    password: AgAc/cwPPcEaUqpVjPsRPQIGZKio02ilgzwh8qXdYWlejN+mfiZocsWSz7q8juQbOKjplqDDpCJYyzoUiPYLOyRzHJz3/CgatA88DyS0H7DJM60v/ipyGTA/vs1fgJx32KypjxVfg9whzn2YMsp2o12Z66jIPIegCMs/Z7ODyo2gXg7O8dZRUFgPCgZ1nhfDWyBk2+3t0l4snzw5Jn+8rYT7hFPh9EkS6qRbTMMSesUynJfb1cG+E38MMDMb7Qhkq2vMRhjSPasUNIDgm9Vbh88r0/o3Os5ZCrzLQw3eOSln/gl7r63riObDdInE2HW1qaIQXLSjevBGEooaLkwLoa853RovrHsQO3oHVkMwmJ7ILLHdUueZ8rpq0Zhcrtxx1vNRLR7xFL0qsU9a4ZnHo2BwYbcfm2QEzenfluj4AQEOgUGuRV1ey7FTWs6TA+d763NK5rXV9GFZI6FyPQfRs34Hs5dgsCx+iTpgf5waVZbWv7xKqaBtzd9qvv/RGnYKHZXfQilbDlMy9ySN7uCa41v+pu3W9pi70rlUHy3GR689OnUY+L/74iNeukubsCKe4gbD8PcQEmqeOH4V+/dyBZKN9zwbT0nrpDgVAVFzN8BeGPTuZFfM+5KI4Y2e2s522UxlGhwPkofdnCqzrcBopMntW4eJXKRnMa+naNCArRgJ7VM4yxfHgL9S9nK3gqK+3sMobs8oey64VJermJ95MjCQK/NO4Hy0o1z394hEHR0Afw==
  template:
    metadata:
      name: device-broker
      namespace: hyrox
