apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/component: broker
    app.kubernetes.io/part-of: hyrox-platform
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: mosquitto
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
