---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: processor-broker
  namespace: hyrox
spec:
  encryptedData:
    password: AgACMKt5GF+eyeIwJ91FYmGOgWkgQW+rO8aD2e50dJ1SAwC2Cig8Ynp027YiL1T+rZcslB1DyYrbmRMCsc4bTw1IUglo/L4mzcQB89mqBU1KbtdbOrja2egCxsI93wQcTPyDLgPiljOaEAeEBD6zJW8BwO5iXtQFe/WS4gOkUiZJPgSLvwqc7r+F/9Pmt8RBoHV5kF28qwteRIkzy1WsIO/rN/T8j+b6E72L4B5/Sj9+7k0+JjewBa8GipGKY0kIz66ZQ84VC1s/1cUItooPxEkgBWoIpF1rfL147cQ83R92WNfd4DC2y4tQKsRmtohXAz1j/gFOKNkhWxPfsYP/LivbYCIbfyZbsGfkL/yvyuYi6aVIzHCUYA5M07AMiH7oOYM+ZDjQQG9MkUFf+dBxxwWzFSvdP+84DRb0YGtb3nz0X+938AQe+qM9vL1irW6JLXYkzb+iNo7TYp6w0Wsmyp5AnUJD106kyQpw/hwo+ZKwfgPR1Z1vneE4Z1P1/P3LNQCnjYANjNpUbwgV2Iwb6TeC4MKU0xCPsRL2Yb/VsPKcNhaZIvdFIMBpntfWnWvDbfbpDLRaPi1GhvhCt9w6gVkD4qtUyE1jJqf+Qg/DWSPU+cBI8+gjNpmZeD+/zTFNiipoJagNtDzPLoD0iLSaXe6ISI9WJbjbPv9rwINX0BFPJL16HCgUDnGm8Dsre1v6vvJ9QUhVLXHl/uzTJeVtmmwp7H+2spmQPAGHzSlUrQNlJw==
    username: AgCw1zPVurACIBhyr8B80SOzKh4NGoQffOy4ku/okP4H0+iGXBzoCOauLxiy3WFBXTzj/cNrIA9m+Vu+27Z10rTb7vwjWWbL+ANMjw0AU/3+cllSSLUZkPxzGVz8UpENR4aIOwh7POUmKXdydOFxRsl3tI338w2vnHOmzPSiBmZ0ULqrMUsl0iuumeFVfDZXkXmNJx53ujAR8PJ1OxPd3NirHoTd83EwxbPHfkS1/NFv2D9poKlswHDZJL+zXGw/sYeYOjVh4c2+W3C+8uAk7hJCSgyorx/RtBltc+eR8m7pb2+cHZRyEA5CkMu/i+FkNWzrsYMaMWtU1+JtSIPCcgdCgjPLoULxB+3xMMe1IUovdfuWkyDYzIJqzEI/KripHqPzNWQnqqAnDyMEAlKd6ACl4mOEgPF9ujOTXFCgovjG0Kk5gF/HDO/T3Ya1ehPaTKcPKLBQSkiFZYySR0bJgqjrmDREVwIp660/i4BeCJk6MHDgl1lPeVqajRmnLcsUv4lr2x0fTLyePOFGumGHVwICKQPATxIReNrbiQZhpbzyDmbCo257sM9veBAdRkXWbiba+exZw5Db5KX/gtxnPAY7E/BBxfh7YgqhTVf3nJhvF7BOYXqlkAtd1H48RH/IYozTpG5vU+tm2D/xGatbD1knLSaGdtreX3Kj5oy23Z2RgBPAzRdQ1BVTrHQxPq819bi8R31FvFEAIic=
  template:
    metadata:
      name: processor-broker
      namespace: hyrox
