# Credenciales de descarga del registro privado (DigitalOcean Container
# Registry), cifradas con la clave del controller de Sealed Secrets. Las usan
# los pods del procesador y de mosquitto para descargar sus imagenes de
# registry.digitalocean.com/haritzblanco. Regenerar (las credenciales de DOCR
# caducan y hay que refrescarlas):
#   doctl registry kubernetes-manifest --namespace hyrox | kubeseal --format yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-haritzblanco
  namespace: hyrox
  labels:
    app.kubernetes.io/part-of: hyrox-platform
spec:
  encryptedData:
    .dockerconfigjson: AgANw4trUoDibkJ9+EWB1WzNSQEy7C89KMzbI+ddAwekqRDA0SGHoodxkWrMxeR6C9KqdFHDFpq/+XiqykyhQSApeufIz32ox3yHDI9nyJomce1tU0I86NFlXy82PRGYcNDIci0FEcKCXhCBSTerKYvqqsPffAVk11iJZxCGgw+7QnTT88t4D07vfxVN5z0QicSfkQGq4k7mtD2tRtByeBNcDfDXbJNT1ukPfXXGVyvydrp34h3oem67ZAYIFUb87qvdHEFCxbANA2E+UM73PYHHBrJAecZGW5i4ts+Q+qkBBTCwzEdqeEjf6HL47oRKLPW/viwNj55e0NF6SiaEz4vbwfL+b21yFOX3ksaoW0SHYtuVZXm8oO6pOe96SisiyR0w+ae4Iza4YEJ/nhQD2ZB3KrtpgBvZ4mJh8BY8tXNDApoSOZ9eSzzht6esxgHi4BwoMbh8UpdNkso8KGnqLfsFpX8S2VtMEUqlnUdQ37Onu+10j4IMCETbwwRzVXbfu1KCCrvzUjLFA4iGNflawF3K/BBtj5bbAPMKCsYg1A+2yH3HChqoHKRvIhijgER3U7IPsz3IkhhnRo81L8rr1boAaZZZp89EbOjFKHn+HuacaSlZCYdnF7tlhrxPPGtXhlcJrcdfi0G/v2UumCNZ2lOnfQdFkXSwHnCp4YfoazIlRXc0yVl1rAXv3w2PUev5XxVAvEEtenD04zgAsXqJY+S62e0n4IbDOljk7WHiiR3cHubCBMLD+KrocQC9n4dErW26KMmlgxKjVQgTOT8s/IyEYFVDfX5TlVXVflZtqP829IcusSk9HFd8ADTWqxhVoFnFZ4BllYEzmvqcTL85H57pl4qYGciUCDnSqZPQu303ilbNJQilBEFXHorXl9hFsZukODYaLYobjIsq4sytfmf3gIUB//vddxXUt1qJzITrLvw1og==
  template:
    metadata:
      name: registry-haritzblanco
      namespace: hyrox
      labels:
        app.kubernetes.io/part-of: hyrox-platform
    type: kubernetes.io/dockerconfigjson
