# Credenciales de descarga del registro privado (DigitalOcean Container
# Registry), cifradas con la clave del controller de Sealed Secrets. Las usan
# los pods del procesador y de mosquitto para descargar sus imagenes de
# registry.digitalocean.com/haritzblanco. Regenerar (las credenciales de DOCR
# caducan y hay que refrescarlas):
#   doctl registry kubernetes-manifest --namespace hyrox | kubeseal --format yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-haritzblanco
  namespace: hyrox
  labels:
    app.kubernetes.io/part-of: hyrox-platform
spec:
  encryptedData:
    .dockerconfigjson: AgA1+FRrohRQpOgVYo9MMKfcFFu256F//9pj7D5DhwFvqSdiiZjzNP3Vo+BSyKO6ZdiuN+GymCknfP5GPtejWrv9Q8Ae/EgCQpbWENdNlsz8EgpMqfrMpl5OUEFwPn1BHryZH3Xo5Yhggr80RaxozzvS2BhJ5LFqSDaqz3DCJESIYhQy7fwYY3R0aWhgF7UYBLG23I8E1so8Z2Gx1T2CjmcTMgMewoUtnFG9buXGjI6tcDltu4tENWNnMT9X8Igna0KP4j5mJM3FFPExCagpKSwcVnVHtWbJNVdVAeqUSyf6Zkz8aAuJ4v/c6N1UmeZB50+hL6GhfPj13hUydqUUYB8naE6KpM6oBbWeMM/SFIAkaMhgaLj8g2aslt+HS9VgQNm9eiuULM8Tgl1wjKCojAjLM+2vZhfyJuL14f4ModsQEmmodnIH/ubfGgohojZAg7rCVG0ncXBKrQDq+sMS3NSSMwLFMR8GNan8FHAegh31nbgIL4KQ6VPBSrljhnmLaDcI+RNrY8gxomJloU5LUjLIX2oJMUjp3n2Onjvd6O4IJac1MdSzmdtILuPP/7YZXJqmfHWZsGwq2iDexAbT+gAx2ry8DyTcwBFJq1KTSXlkunkZdkbykAgZ61oSAzJLZT78+UggTGKEwvjcE+BuK94kZNK7AriFXwCr0SxTRIWlM7WO3bc8ecHS2+WxSMn/2B4e93y51yih0pkp3vPPvyE80CX9ZJ+G44ol3FxGKOB5D78q2rJ9PfQGJWrha9ZbIv51VBbyPbmDf7K7ZWqhI0nhtWh2MTzk/rdtJ5ICOXWfYzybTsMo2ZezCbHr1gB0OWvrqVjIzWanWmlgt7u03n/TaFuV+N3J/H9xkpfjkUPXeZGl/V0j5Ozn/zzSGJ3VMNj2NF4Vn3PcJjIwJ3zZHLB3mjdfZGle1MePccosIpqNVmc3Mg==
  template:
    metadata:
      name: registry-haritzblanco
      namespace: hyrox
      labels:
        app.kubernetes.io/part-of: hyrox-platform
    type: kubernetes.io/dockerconfigjson
