apiVersion: v1
kind: Secret
metadata:
  name: influxdb-auth
  namespace: hyrox
  labels:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/part-of: hyrox-platform
type: Opaque
stringData:
  username: admin
  password: haritzblanco
  org: hyrox
  bucket: telemetry
  token: token1234567890