apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: hyrox-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage }}
  storageClassName: local-path
