# Credenciales de Grafana cifradas con la clave publica del controller de
# Sealed Secrets, igual que las de InfluxDB. El token es el mismo que usa el
# procesador, acotado a lectura y escritura de buckets de la organizacion.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-auth
  namespace: hyrox
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: hyrox-platform
spec:
  encryptedData:
    admin-password: AgBUTy1/+VTz6RZ5OnxbVJ+PfHR3g7OoT5l9GQcFwfJiff6nzNNMnafkG0SJ9xUQcpcwfS3Bv8/xYQ7H3hR+AtPHM+Y7sYnj2o2A/JhPNyzGMr67fD3DdkJAszc+tKVqoceb9ow6bMk58TS+Az4B32yPR4vE05DsJhMJ1iZSv3513T4JrqL6WxhHE0yDpCzeOqjGjlS8Dq89PlJMRwgRu3fwrHQqTbXu+eMiWTuv4N/WSZPWdYmcrB1cCRvd67gopsdicPNGAxYccWVfZidsdo04IPVaPTtcua8Y3db1kfp1XjVt+VQRVJdGSx0Idr6E+S4yOfT8GXJNCLOGPoEgLmEnwP72s790b5ecMr4CottDSl/JnZAt6xGIIonO2Pqfx9dKtJ/l9uF7PHrWL1wEBCwDTvTI7JrbeMTWQzE8Ae+sDT/9QB/LQwg6vSHsFzBeKpzwX4zVxwBBw86ZJKD4j6wyLW8pHv3TXg1DiQ8DS4Bgiew7YR5ZMiXvdBbMjXN+Cn7I9Ot8RCAxrH967DK4Woxvb+i30UgWpBQZ2T9FWzzjTYXXQAyrCuogmaPCvhU29tTVqzuHwabsGxB0CT8cjP0F0GN+4cEijvchrkTKHltl+IcdkgEZJtNgq+TIUv/Wf53GJ/SGQ35HcF2QMfjPbG+R0TCbadgHKayMTQS7CEvx7uQXIgm1Nwo0+PDAloyT3usJswe45HDSe1bXnvys1zSdrw8nhitzp2Q=
    influx-token: AgBsuCCbG6c3u2iXBEc2/6xSd47Fvmdxl3OLScucewD08q0WFY8Pxm4IS1nyZubj4+M3jQB+KYA9lx4cZOoRVIivaU17JO0sLEnR7djKVopkcW0xk7FV1wTgS8IqrX7b4vJ80Z2chZFyPEMl2DzLU0ERbYdv126/EykkSrTHqqgCCJTRdsMidytBXyBJEsvclWO4G1OQZk0YcM6mLRReKwjG9ygG4VAEKfoOBJpNOyQaLopVBLcQoMzgzMGPgR3F5jkCOfaV8bMeXensada2ziCU9qMt+6z20G0L/AIjGNtIgbC3zFJ7dMvQQm3HdFhpFGmki5jGaI6wuN/uNwtXE1Coy7F6asPVNmrFF6OOoGNIQR4CYksy8s2t5OAD5imDMdohReDJEiYKDozUlUxiUoCec9svWelXAzAtd/THPhqCDoG5QkQUNHCvXb66U3hxqgcRK2p4aMleJlbn7gDUxwCjxG6xdxaZf/teJQTt4c0p9J7hxMQB+J8mDsUa7eRDRWyzMkzo+RyQl/2m5jYFDOLnnJOOMST2gvyAri8oYgRIVHg5zmtYEY1maKZxyY8LBQZl9me/41pL+jl8s8x2X2C1o2yXJ4LYwbVfAXiSaJhOrW9SnXLtW2+z3wWaMLh0IUa9yerayddVLAHvmxCS23/skSpKAzDbjy74RmBvYqz/Ni0M93TOLkxPOjfqO6lpCgNOOD+flRhu2sZd59Gl+JwnIXMrFMqUBUezux7br2scG/pGO3tJ3mlg29NqQ5I7IEgIEbHYrAwKBZYNUM2XL48qOiCNNCErEQ0E2QJ9GEd9eKstjyZjx10V
  template:
    metadata:
      name: grafana-auth
      namespace: hyrox
      labels:
        app.kubernetes.io/name: grafana
        app.kubernetes.io/part-of: hyrox-platform
