apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data
  labels:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/part-of: hyrox-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage }}
