apiVersion: v1
kind: Secret
metadata:
  name: influxdb-auth
  labels:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/part-of: hyrox-platform
type: Opaque
stringData:
  username: {{ .Values.auth.username }}
  password: {{ .Values.auth.password }}
  org: {{ .Values.auth.org }}
  bucket: {{ .Values.auth.bucket }}
  token: {{ .Values.auth.token }}
