apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: hyrox-platform
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: influxdb
  ports:
    - name: http
      port: 8086
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
